run:
	./hcov.sh

clean:
	rm -fr \
               *.bam* \
               *.vcf* \
               *-consensus* \
               *-coverage.txt \
               *-read-count.txt \
               *-alignment.fasta \
               tmp \
               slurm-*.out
