.PHONY: all, run, force, status, cancel, unfinished, clean-refseq clean-rvdb clean
.PHONY: html, html-refseq, html-rvdb, tar, tar-refseq, tar-rvdb

REFSEQ_DB := /rds/project/djs200/rds-djs200-acorg/bt/root/share/ncbi/viral-refseq/viral-protein-20180717/viral.protein.fasta
RVDB_DB :=   /rds/project/djs200/rds-djs200-acorg/bt/root/share/rvdb/U-RVDBv14.0-prot.fasta

all:
	@echo "There is no default make target. Use 'make run' to run the SLURM pipeline, or make html, or make tar."

html: html-refseq html-rvdb

html-refseq:
	find 1* -name summary-proteins | \
        grep 04-panel-refseq | \
        proteins-to-pathogens.py \
            --format fastq \
            --html \
            --sampleNameRegex '^[0-9]{6}/([0-9]{6}_[0-9]{2})' \
            --pathogenType viral \
            --proteinFastaFilename $(REFSEQ_DB) \
            --pathogenPanelFilename virus-refseq.png \
            --sampleIndexFilename samples-refseq.index \
            --pathogenIndexFilename pathogens-refseq.index \
            > index-refseq.html

html-rvdb:
	find 1* -name summary-proteins | \
        grep 04-panel-rvdb | \
        proteins-to-pathogens.py \
            --format fastq \
            --html \
            --sampleNameRegex '^[0-9]{6}/([0-9]{6}_[0-9]{2})' \
            --pathogenType viral \
            --proteinFastaFilename $(REFSEQ_DB) \
            --pathogenPanelFilename virus-rvdb.png \
            --sampleIndexFilename samples-rvdb.index \
            --pathogenIndexFilename pathogens-rvdb.index \
            > index-rvdb.html

tar: tar-refseq tar-rvdb

tar-refseq:
	tar cfj results-refseq.tar.bz2 */*/pipelines/standard/04-panel-refseq/out index-refseq.html virus-refseq.png {samples,pathogens}-refseq.index

tar-rvdb:
	tar cfj results-rvdb.tar.bz2   */*/pipelines/standard/04-panel-rvdb/out   index-rvdb.html virus-rvdb.png {samples,pathogens}-rvdb.index

clean-refseq:
	rm -f \
               results-refseq.tar.bz2 \
               {samples,pathogens}-refseq.index \
               virus-refseq.png \
               index-refseq.html

clean-rvdb:
	rm -f \
               results-rvdb.tar.bz2 \
               {samples,pathogens}-rvdb.index \
               virus-rvdb.png \
               index-rvdb.html

clean: clean-refseq clean-rvdb
